App\Entity\User:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 50
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.